### ISSUE TITLE
DOM XSS on http://easy-putio.baptiste-vincent.fr/get_token.html

### ISSUE THREAD

**Issue by mikispag** [Baptvincent/Easy-Put.io#6]
Hello,

there is a DOM XSS vulnerability on http://easy-putio.baptiste-vincent.fr/get_token.html.

Proof of concept:
```
http://easy-putio.baptiste-vincent.fr/get_token.html#access_token=<img src=x onerror=alert(document.cookie)>
```

This can be very easily fixed by replacing

```
document.getElementById('token').innerHTML=access_token;
```

with:

```
document.getElementById('token').textContent = access_token;
```

**Comment by Baptvincent** [comment]
Thank you, I fixed it ;)

-- 
Baptiste Vincent

On July 31, 2015 at 5:44:31 PM, Michele Spagnuolo (notifications@github.com) wrote:

Hello,

there is a DOM XSS vulnerability on http://easy-putio.baptiste-vincent.fr/get_token.html.

Proof of concept:

http://easy-putio.baptiste-vincent.fr/get_token.html#access_token=<img src=x onerror=alert(document.cookie)>

This can be very easily fixed by replacing

document.getElementById('token').innerHTML=access_token;

with:

document.getElementById('token').textContent = access_token;
